{% set name = "psf" %}
{% set version = "2024.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psf-{{ version }}.tar.gz
  sha256: 548622f6160dc2d34e51241e2ef55f9fc28207d5bd55379f6031b903af71dca6

build:
  skip: true  # [py<=38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy >=1.23.5
    - pip
    - python
    - setuptools >=18.0
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - psf
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Point Spread Function calculations for fluorescence microscopy
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/psf/

extra:
  recipe-maintainers:
    - goanpeca
