{% set name = "psf" %}
{% set version = "2022.9.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psf-{{ version }}.tar.gz
  sha256: 8052d3669b6062015243c51f81ae22769f6a30d4ef2df09ffc154aca76faa2f9

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy >=1.15.1
    - pip
    - python
    - setuptools >=18.0
  run:
    - numpy >=1.15.1
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - psf
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Point Spread Function calculations for fluorescence microscopy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
