{% set name = "psf" %}
{% set version = "2021.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psf-{{ version }}.tar.gz
  sha256: 49c7f045970fb0b91fd9c42bd6e07eab174c7026a68d90583323fc498fa9669f

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy >=1.15.1
    - pip
    - python
    - setuptools >=18.0
  run:
    - numpy >=1.15.1
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - psf
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Point Spread Function calculations for fluorescence microscopy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
